# Generated by Django 6.0.1 on 2026-01-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_emailotp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
