# Generated by Django 6.0.1 on 2026-01-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_emailotp_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
