# Generated by Django 6.0.1 on 2026-01-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_blogcategory_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('DESKTOP APP', 'Desktop App'), ('WEB DEV', 'Web Dev'), ('NETWORK SEC', 'Network Sec'), ('OSINT TOOLS', 'OSINT Tools'), ('INFOSEC', 'InfoSec'), ('WEB APP', 'Web App'), ('OTHER', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Research', 'Research'), ('Coming Soon', 'Coming Soon'), ('Legacy', 'Legacy')], default='Active', max_length=50)),
                ('tagline', models.CharField(max_length=300)),
                ('link', models.URLField(blank=True, help_text='External link (GitHub, Deployment)', null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which projects appear')),
            ],
            options={
                'ordering': ['-order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='note',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='note',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='Field Note', max_length=200),
        ),
    ]
