# Generated by Django 6.0 on 2026-01-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_apikey_apikeyusage'),
        ('api', '0014_blogpost_word_count'),
    ]

    operations = [
    ]
